accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

blog/urls.py
from django.urls import path
from .views import (
                        PublicationListView, 
                        PublicationDetailView,
                        PublicationCreateView,
                        PublicationUpdateView,
                        PublicationDeleteView,
                    )


urlpatterns = [
    path('', PublicationListView.as_view(), name='publications-list'),
    path('Publication/<int:pk>/', PublicationDetailView.as_view(), name='publication-detail'),
    path('Publication/new/', PublicationCreateView.as_view(), name='publication-create'),
    path('Publication/<int:pk>/update/', PublicationUpdateView.as_view(), name='publication-update'),
    path('Publication/<int:pk>/delete/', PublicationDeleteView.as_view(), name='publication-delete'),
]
   

django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')), 
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Publication(models.Model):
    title = models.CharField(max_length=30)
    body = models.TextField()
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    date = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('publication-detail', kwargs={'pk': self.pk})
    
   

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

# Create your views here.

blog/views.py
from .models import Publication
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        UserPassesTestMixin
                                        )

# Create your views here.

class PublicationListView(ListView):
    model = Publication
    template_name = 'publications-list.html'

class PublicationDetailView(LoginRequiredMixin,DetailView):
    model = Publication
    template_name = 'publication-detail.html'

class PublicationCreateView(LoginRequiredMixin,CreateView):
    model = Publication
    template_name = 'publication-create.html'
    fields = ['title', 'body', 'author']

class PublicationUpdateView(LoginRequiredMixin,UserPassesTestMixin, UpdateView):
    model = Publication
    template_name = 'publication-update.html'
    fields = ['title', 'body', 'author']

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user

class  PublicationDeleteView(LoginRequiredMixin,UserPassesTestMixin,DeleteView):
    model = Publication
    template_name = 'publication-delete.html'
    fields = ['title', 'body', 'author']
    success_url = reverse_lazy('publications-list')

    def test_func(self):    
        obj = self.get_object() 
        return obj.author == self.request.user  # only the author can delete the publication

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Blog</title>
    <!-- Bootstrap  CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style></style>
</head>
<body>
    <nav>

    </nav>
    <header>
        <h1><a href="{% url 'publications-list' %}">Blog Django</a></h1>
    <div> <a href="{% url 'publication-create' %}" class="btn btn-primary">Nueva publicación</a></div>
    </header>
        {% if user.is_authenticated %}
        <p>Hola {{ user.username }}</p>
        <form action="{% url 'logout' %}" method="post" class="d-inline">
            {% csrf_token %}
            <button type="submit">Cerrar sesión</button>
        </form>
    {% else %}
        <p><a href="{% url 'login' %}" class="btn btn-secondary">Iniciar sesión</a>
        <a href="{% url 'signup' %}" class="btn btn-primary">Registrarse</a></p>
    {% endif %}
    
    <main class="container">
        {% block content %}
        
        {% endblock %}
        </main>
    <!-- Bootstrap JS  -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
</body>
</html>

templates/publication-create.html
{% extends "_base.html" %}

{% block content %}
    <h2>Nueva publicación</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Publicar</button>
    </form>
{% endblock content %}

templates/publication-delete.html
{% extends "_base.html" %}	

{% block content %}
    <h2>¿Desea eliminar la publicación "{{ publication.title }}"? </h2>
    <form method="post">
        {% csrf_token %}                    
       <button type="submit">Si</button>
    </form>                 
{% endblock content %}

templates/publication-detail.html
{% extends "_base.html" %}

{% block content %}
    <h2>{{ publication.title }}</h2>
    <p>{{ publication.author }}</p>
    <p>{{ publication.body }}</p>
    {% if publication.author.pk == request.user.pk %}
        <a href="{% url 'publication-update' publication.pk %}">Editar</a> 
        <!-- button eliminar -->
        <a href="{% url 'publication-delete' publication.pk %}">Eliminar</a>
    {% endif %}
{% endblock content %}

templates/publication-update.html
{%  extends "_base.html" %}

{% block content %}
    <h2>Editar publicación</h2>
    <form method="post"> 
        {% csrf_token %}
        {{ form.as_p }}                                                 
        <button type="submit">Guardar cambios</button>
    </form>
    <a href="{% url 'publications-list' %}">Cancelar</a>
{% endblock content %}

templates/publications-list.html
{% extends "_base.html" %}

{% block content %}
    {%  for post in publication_list %}
    <h2> <a href="{% url 'publication-detail' post.pk %}"> {{ post.title }}</a></h2>
        <p>{{ post.author }} </p>
    {% endfor %}
{% endblock %}